### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kikoueeeeeeee2882** [david09baz/Snake-AI-NeuralNetwork#1]
There is a bug in the .exe file so that when I force close it with task manager it restarts my pc and puts a blue screen

**Comment by trpxvbz** [comment]
Can you leave me some more details like what is your operating system:
Copy And Paste this
OS:
Computer Model:
How old is your computer:
Have the blue screens happened before:

**Comment by kikoueeeeeeee2882** [comment]
OS: computer
Computer model: MSI
How old?: 11 years old
Have the blue screens happended before: Yes

**Comment by trpxvbz** [comment]
I'm quite sure its only your computer doing that because its normal on a 11 year old computer to have a blue screen. Its prob only your software or smh.

**Comment by trpxvbz** [comment]
I am closing this issue now.

**Comment by kikoueeeeeeee2882** [comment]
Noo
